# Dictionary

In [4]:
kode_negara ={'India' : 'ind', 'Indonesia' : 'ina', 'United States' : 'usa'}
print(kode_negara)

{'India': 'ind', 'Indonesia': 'ina', 'United States': 'usa'}


In [5]:
print (type(kode_negara))

<class 'dict'>


In [6]:
print(kode_negara['India'])

ind


In [8]:
kode_negara['China'] = 'chn'
print(kode_negara)

{'India': 'ind', 'Indonesia': 'ina', 'United States': 'usa', 'China': 'chn'}


In [9]:
kode_negara['Indonesia'] = 'idn'
print(kode_negara)

{'India': 'ind', 'Indonesia': 'idn', 'United States': 'usa', 'China': 'chn'}


In [10]:
del kode_negara['United States']
print(kode_negara)

{'India': 'ind', 'Indonesia': 'idn', 'China': 'chn'}


In [11]:
print(len(kode_negara))

3


In [12]:
print('India' in kode_negara)

True


In [14]:
print ('Germany' in kode_negara)

False


In [15]:
kunci = kode_negara.keys()
print(kunci)

dict_keys(['India', 'Indonesia', 'China'])


In [16]:
nilai = kode_negara.values()
print(nilai)

dict_values(['ind', 'idn', 'chn'])


In [18]:
pasangan = kode_negara.items()
print(pasangan)

dict_items([('India', 'ind'), ('Indonesia', 'idn'), ('China', 'chn')])


In [20]:
student = {
    'nama' : "Arief Fadhillah R",
    'usia' : 20,
    'nilai': {
        'matematika' : 85,
        'fisika'     : 90,
        'kimia'      : 80
    }
}
print(student)

{'nama': 'Arief Fadhillah R', 'usia': 20, 'nilai': {'matematika': 85, 'fisika': 90, 'kimia': 80}}


In [21]:
print("Nilai Fisika :", student['nilai']['fisika'])

Nilai Fisika : 90


In [22]:
data1 = {'nama' : 'Fadhil', 'usia' : '20', 'pekerjaan' : 'progammer'}
data2 = data1.copy()
print(data2)

{'nama': 'Fadhil', 'usia': '20', 'pekerjaan': 'progammer'}


In [23]:
usia = data1.get('usia')
print(usia)

20


In [24]:
data1.update({'gaji' : '5000000', 'alamat' : 'bekasi'})
print(data1)

{'nama': 'Fadhil', 'usia': '20', 'pekerjaan': 'progammer', 'gaji': '5000000', 'alamat': 'bekasi'}


In [28]:
pekerjaan = data1.pop('pekerjaan')
print(data1)

{'nama': 'Fadhil', 'usia': '20', 'gaji': '5000000', 'alamat': 'bekasi'}


In [30]:
item = data1.popitem()
print(data1)

{'nama': 'Fadhil', 'usia': '20', 'gaji': '5000000'}


In [31]:
data1.clear()
print(data1)

{}


# Numpy Array

In [32]:
import numpy as np

In [33]:
angka = [12, 3, 5, 6, 0, -1, 2]
number = np.array(angka)
print(number)
print(type(number))

[12  3  5  6  0 -1  2]
<class 'numpy.ndarray'>


In [35]:
enol = np.zeros((3,3))
print(enol)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
satu = np.ones((2,3))
print(satu)

[[1. 1. 1.]
 [1. 1. 1.]]


In [38]:
deret = np.arange(1,20,3)
print(deret)

[ 1  4  7 10 13 16 19]


In [49]:
lang = np.array(['id','en','jp','cn','ru','kr','th'])


In [41]:
print(lang[0])

id


In [42]:
print(lang[-1])

th


In [47]:
print(lang[1:4])

['en' 'jp' 'cn']


In [50]:
print(lang[3:])

['cn' 'ru' 'kr' 'th']


In [51]:
print(lang[:5])

['id' 'en' 'jp' 'cn' 'ru']


In [53]:
A = np.array ([[81,24,36],
               [43,67,12],
               [75,91,58]
               ])

In [54]:
print(A)

[[81 24 36]
 [43 67 12]
 [75 91 58]]


In [57]:
print(A[0,2])

36


In [59]:
print(A[1,2])

12


In [60]:
X = np.array([[1,2,3], [4,5,6], [7,8,9]])
Y = np.array([[2,2,2], [2,2,2], [2,2,2]])

skalar = 3

In [62]:
z = X + Y

In [63]:
print(z)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [64]:
B = z - X
print(B)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [65]:
C = X * skalar
print(C)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [66]:
J = np.matmul(X,Y)
print(J)

[[12 12 12]
 [30 30 30]
 [48 48 48]]
